### ISSUE TITLE
Cannot allocate more than 13G of swap

### ISSUE THREAD

**Issue by windowsair** [actionhippie/swap-space#3]
Hi, @tboerger

First of all thank you for this library, it's very convenient for me to set up swap.

But there seems to be two problems here:

1. It is not possible to allocate more than 12G of swap file, when setting more than 12G, only 12G is actually allocated.
2. The default swap path seems to be incorrect. It is expected to be /swapfile, but it is actually `/mnt/swapfile`.

I haven't investigated this yet, but I think the root cause of both problems lies in second problem. If you think it is appropriate, I will spend some time to investigate this and try to submit a PR.

**Comment by tboerger** [comment]
I never tried to allocate such a big swap. The default for the action is /swapfile, but first it detects an already existing swap. Please take a look at action.yml, everything is in there.

**Comment by tboerger** [comment]
I can't reproduce your issue, I have commit this workflow and received the following result

### tryout.yml

```yml
name: tryout

"on":
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actionhippie/swap-space@v1
        with:
          size: 20G
```

### output

```
Run actionhippie/swap-space@v1
Run echo "Memory and swap:"
Memory and swap:
               total        used        free      shared  buff/cache   available
Mem:            15Gi       576Mi        13Gi        21Mi       1.2Gi        14Gi
Swap:          4.0Gi          0B       4.0Gi

NAME          TYPE SIZE USED PRIO
/mnt/swapfile file   4G   0B   -2

Run export SWAP_FILE=$(swapon --show=NAME | tail -n 1)
Setting up swapspace version 1, size = 20 GiB (21474832384 bytes)
no label, UUID=b1f6da2f-c24a-4b01-afd8-cb40a26fe8ea
Run echo "Memory and swap:"
Memory and swap:
               total        used        free      shared  buff/cache   available
Mem:            15Gi       588Mi        13Gi        21Mi       1.2Gi        14Gi
Swap:           19Gi          0B        19Gi

NAME          TYPE SIZE USED PRIO
/mnt/swapfile file  20G   0B   -2
```
